# Based on the pure workflow by lukka: <https://github.com/lukka/CppBuildTasks-Validation/blob/master/.github/workflows/hosted-pure-workflow.yml>
# Released under the MIT license.

name: Build avpipe
on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
      VCPKG_ROOT: "${{ github.workspace }}/3rd-party/vcpkg"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: lukka/get-cmake@latest

    - uses: actions/cache@v2
      with:
        path: |
          ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/
          ${{ env.VCPKG_ROOT }}
          !${{ env.VCPKG_ROOT }}/buildtrees
          !${{ env.VCPKG_ROOT }}/packages
          !${{ env.VCPKG_ROOT }}/downloads
        key: |
          ${{ hashFiles( 'vcpkg.json' ) }}-${{ hashFiles( '.git/modules/vcpkg/HEAD' )}}-${{ matrix.triplet }}-invalidate

    - uses: ilammy/msvc-dev-cmd@v1

    # nasm is needed for ffmpeg
    # autoconf, automake, autopoint, libtool, and gperf are needed for fontconfig
    # libx11-dev, libmesa-dev, libxi-dev, and libxext-dev are needed for angle
    # the rest is needed for qt5
    # might also need: build-essential curl zip unzip tar
    - name: Set up Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake autopoint libtool nasm gperf libx11-dev libxi-dev libxext-dev libxkbcommon-x11-dev libgl1-mesa-dev libglu1-mesa-dev libfontconfig1-dev libfreetype6-dev libx11-xcb-dev libxfixes-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev

    # autoconf and automake are needed by fontconfig
    # pkg-config is needed for zlib
    # nasm is needed for ffmpeg
    - name: Set up macOS
      if: runner.os == 'macOS'
      run: |
        brew install autoconf automake pkg-config nasm
        # work around <https://github.com/microsoft/vcpkg/issues/10209>
        echo 'set(VCPKG_OSX_DEPLOYMENT_TARGET "10.15")' >> ${{ env.VCPKG_ROOT }}/triplets/x64-osx.cmake

    - name: Install dependencies and configure
      run: |
        cmake -B "${{ env.CMAKE_BUILD_DIR }}" -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: |
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config Release

#
#    - name: Set up Windows
#      if: runner.os == 'Windows'
#      shell: bash
#      run: |
#        vcpkg install boost-iterator:x64-windows ffmpeg:x64-windows qt5:x64-windows
#        echo ::set-env name=CMAKE_FLAGS::"-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
#
#    - name: Set up Linux
#      if: runner.os == 'Linux'
#      run: |
#        sudo apt-get update
#        sudo apt-get install g++-10 libboost-dev qtbase5-dev qtmultimedia5-dev libavformat-dev libavcodec-dev libavdevice-dev libavfilter-dev
#        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
#        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
#        sudo update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-10 100
#        sudo update-alternatives --set gcc /usr/bin/gcc-10
#        sudo update-alternatives --set g++ /usr/bin/g++-10
#        sudo update-alternatives --set cpp-bin /usr/bin/cpp-10
#
#    - name: Set up macOS
#      if: runner.os == 'macOS'
#      run: |
#        brew install pkg-config boost qt ffmpeg
#        echo ::set-env name=Qt5_DIR::"$(brew --prefix qt5)/lib/cmake/Qt5"
#
#    - name: Create Build Directory
#      run: cmake -E make_directory ${{runner.workspace}}/build
#
#    - name: Configure
#      shell: bash
#      working-directory: ${{runner.workspace}}/build
#      run: cmake ../avpipe -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS
#
#    - name: Build
#      working-directory: ${{runner.workspace}}/build
#      run: cmake --build . -v --config Release

    - uses: actions/upload-artifact@v2
      with:
        name: avpipe-${{runner.os}}
        path: ${{runner.workspace}}/build
